spring:
  web:
    resources:
      add-mappings: false  # 정적 리소스 매핑 끄기 (404 응답 시 HTML 반환 방지)
  mvc:
    problemdetails:
      enabled: true  # Spring 3.x의 표준 문제 응답 포맷 활성화
  jwt:
    secret: vmfhaltmskdlstkfkdgodyroqkfwkdbalroqkfwkdbalaaaaaaaaaaaaaaaabbbbb